"use client";
import { Topbar } from "@/components/Topbar";
import { StatusBadge } from "@/components/StatusBadge";
import { transitionOrder, useOrders } from "@/lib/demo-store";
import { brl, shortDate } from "@/lib/format";

export default function Billing(){
  const orders=useOrders().filter((order)=>order.channel==="B2B"&&["READY_FOR_BILLING","BILLING"].includes(order.status));
  const invoiced=useOrders().filter((order)=>order.channel==="B2B"&&order.status==="INVOICED").slice(0,5);
  return <main className="page"><div className="shell"><Topbar mode="FATURAMENTO"/><div className="hero"><div><div className="eyebrow">Pré-faturamento</div><h1 className="title title-small">Fila pronta para digitar.</h1><p className="subtitle">Nesta etapa o fiscal atual continua emitindo a nota. Nosso painel elimina a caça por preço, produto, lote e observação.</p></div><div className="panel panel-soft"><div className="eyebrow">Liberados</div><strong style={{fontSize:34}}>{orders.length}</strong></div></div>
    <div className="stack">{!orders.length&&<div className="notice">Nenhum pedido liberado pelo comercial.</div>}{orders.map((order)=>{const total=order.total ?? order.items.reduce((sum,item)=>sum+(item.unitPrice||0)*item.quantity,0);return <div className="order-card" key={order.id}><div className="order-head"><div><div className="eyebrow">Pedido #{order.number} · {shortDate(order.createdAt)}</div><h2>{order.customerName}</h2><div className="muted">{order.document} · {order.paymentTerms}</div></div><StatusBadge status={order.status}/></div><ul className="order-items">{order.items.map((item)=><li key={item.productId}><span>{item.quantity}× {item.name} · {brl(item.unitPrice||0)}/cx</span><strong>{brl((item.unitPrice||0)*item.quantity)}</strong></li>)}</ul>{order.commercialNote&&<div className="notice" style={{marginTop:14}}><strong>Lote/Data/Obs:</strong> {order.commercialNote}</div>}<div className="total"><span>Total</span><span>{brl(total)}</span></div><div className="row">{order.status==="READY_FOR_BILLING"&&<button className="btn secondary" onClick={()=>transitionOrder(order.id,"BILLING","FATURAMENTO","Digitação iniciada")}>INICIAR DIGITAÇÃO</button>}{order.status==="BILLING"&&<button className="btn success" onClick={()=>transitionOrder(order.id,"INVOICED","FATURAMENTO","Faturado no sistema fiscal")}>MARCAR FATURADO</button>}</div><div className="timeline">{order.events.slice(-5).map((event,index)=><span key={`${event.at}-${index}`}>{event.actor} · {event.type.replace("STATUS_","")}</span>)}</div></div>})}</div>
    {!!invoiced.length&&<div style={{marginTop:26}}><div className="eyebrow">Faturados recentemente</div><div className="grid" style={{marginTop:10}}>{invoiced.map((order)=><div className="panel" style={{gridColumn:"span 4"}} key={order.id}><div className="row-between"><strong>#{order.number} · {order.customerName}</strong><StatusBadge status={order.status}/></div><div className="muted small" style={{marginTop:8}}>{order.document}</div></div>)}</div></div>}
  </div></main>;
}
